% User input
spikeData.files = {'/Volumes/eplab/Personal/Martynas/Spikesorting/kilosort4/MSEL_02717/msel_02717_ICU02a_TimeSeries_32000_Hz_segments_1_12/temp_wh.spikes.cellinfo.mat'; ...
                   '/Volumes/eplab/Personal/Martynas/Spikesorting/kilosort4/MSEL_02717/msel_02717_ICU02a_TimeSeries_32000_Hz_segments_1_12/temp_wh.spikes.cellinfo.mat'; ...
                   '/Volumes/eplab/Personal/Martynas/Spikesorting/kilosort4/MSEL_02717/msel_02717_ICU02a_TimeSeries_32000_Hz_segments_13_24/temp_wh.spikes.cellinfo.mat'; ...
                   '/Volumes/eplab/Personal/Martynas/Spikesorting/kilosort4/MSEL_02717/msel_02717_ICU02a_TimeSeries_32000_Hz_segments_13_24/temp_wh.spikes.cellinfo.mat'};

spikeData.startTimes = [0 0 12*3125 12*3125];

spikeData.existingUnitIDs = [49 59 59 63];

spikeData.newGlobalUnitIDs = [1 1 1 1];

spikeData.newGlobalUnitCh = [5 5 5 5];

spikeData.chLabels = {'LCmicro_0006'; ...
                      'LCmicro_0006'; ...
                      'LCmicro_0006'; ...
                      'LCmicro_0006'};

spikeData.leadLabels = {'LC'; ...
                        'LC'; ...
                        'LC'; ...
                        'LC'};

spikeData.areaLabels = {'WM_hypointensities'; ...
                        'WM_hypointensities'; ...
                        'WM_hypointensities'; ...
                        'WM_hypointensities'};

nwbFile = '/Volumes/data_4TB/msel_02717_ICU02a.nwb';


% Convert spiking data
cellexplorer2nwb(spikeData, nwbFile)