% User input
spikeData.files = {'W:\Personal\Martynas\Spikesorting\kilosort4\MSEL_02717\msel_02717_ICU02a_TimeSeries_32000_Hz_segments_1_12\temp_wh.spikes.cellinfo.mat'; ...
                   'W:\Personal\Martynas\Spikesorting\kilosort4\MSEL_02717\msel_02717_ICU02a_TimeSeries_32000_Hz_segments_1_12\temp_wh.spikes.cellinfo.mat'; ...
                   'W:\Personal\Martynas\Spikesorting\kilosort4\MSEL_02717\msel_02717_ICU02a_TimeSeries_32000_Hz_segments_13_24\temp_wh.spikes.cellinfo.mat'; ...
                   'W:\Personal\Martynas\Spikesorting\kilosort4\MSEL_02717\msel_02717_ICU02a_TimeSeries_32000_Hz_segments_13_24\temp_wh.spikes.cellinfo.mat'};

spikeData.startTimes = [0 0 3125 3125];

spikeData.existingUnitIDs = [49 59 59 63];

spikeData.newGlobalUnitIDs = [1 1 1 1];

spikeData.newGlobalUnitCh = [5 5 5 5];

spikeData.chLabels = {'LCmicro6'; ...
                      'LCmicro6'; ...
                      'LCmicro6'; ...
                      'LCmicro6'};

spikeData.leadLabels = {'LCmicro'; ...
                        'LCmicro'; ...
                        'LCmicro'; ...
                        'LCmicro'};

spikeData.areaLabels = {'WM_hypointensities'; ...
                        'WM_hypointensities'; ...
                        'WM_hypointensities'; ...
                        'WM_hypointensities'};

nwbFile = 'W:\Personal\Martynas\NWB\MSEL_02717\msel_02717_ICU02a.nwb';


% Convert spiking data
cellexplorer2nwb(spikeData, nwbFile)